	;	This file is auto-generated by the LogoCreator program
	;	Created: 25/08/2026 11:54 (UTC)

	.charmap $54, $54	;	T
	.charmap $45, $45	;	E
	.charmap $41, $41	;	A
	.charmap $53, $53	;	S
	.charmap $44, $44	;	D
	.charmap $55, $55	;	U
	.charmap $52, $52	;	R
	.charmap $49, $49	;	I
	.charmap $42, $42	;	B
	.charmap $4e, $4e	;	N
	.charmap $43, $43	;	C
	.charmap $4c, $4c	;	L
	.charmap $4f, $4f	;	O
	.charmap $47, $47	;	G
	.charmap $50, $50	;	P
	.charmap $27, $27	;	'
