	;	This file is auto-generated by the LogoCreator program
	;	Created: 25/08/2026 11:54 (UTC)

.include "LogoCharacterMap.asm"

strLogo1
.export strLogo1
	db	"COPRO BAT'N'BALL"
	db	$ff

strLogo2
.export strLogo2
	db	"TUBE NOT RESPONDING"
	db	$ff

strLogo3
.export strLogo3
	db	"LOADING"
	db	$ff

.include "LogoCharacterMapRevert.asm"
