	;	This file is auto-generated by the LogoCreator program
	;	Created: 25/08/2026 11:54 (UTC)

LogoCharacterPointers
	dw	LogoCharacterDefinitions
	dw	LogoCharacterDefinitions + $14
	dw	LogoCharacterDefinitions + $28
	dw	LogoCharacterDefinitions + $42
	dw	LogoCharacterDefinitions + $58
	dw	LogoCharacterDefinitions + $6e
	dw	LogoCharacterDefinitions + $84
	dw	LogoCharacterDefinitions + $98
	dw	LogoCharacterDefinitions + $9c
	dw	LogoCharacterDefinitions + $b0
	dw	LogoCharacterDefinitions + $c6
	dw	LogoCharacterDefinitions + $de
	dw	LogoCharacterDefinitions + $ee
	dw	LogoCharacterDefinitions + $108
	dw	LogoCharacterDefinitions + $122
	dw	LogoCharacterDefinitions + $136
