	;	This file is auto-generated by the LogoCreator program
	;	Created: 25/08/2026 11:54 (UTC)

	.charmap $54, $00	;	T
	.charmap $45, $01	;	E
	.charmap $41, $02	;	A
	.charmap $53, $03	;	S
	.charmap $44, $04	;	D
	.charmap $55, $05	;	U
	.charmap $52, $06	;	R
	.charmap $49, $07	;	I
	.charmap $42, $08	;	B
	.charmap $4e, $09	;	N
	.charmap $43, $0a	;	C
	.charmap $4c, $0b	;	L
	.charmap $4f, $0c	;	O
	.charmap $47, $0d	;	G
	.charmap $50, $0e	;	P
	.charmap $27, $0f	;	'
