	;	This file is auto-generated by the LogoCreator program
	;	Created: 25/08/2026 11:54 (UTC)

LogoCharacterWidths
	db	10	;	T
	db	10	;	E
	db	13	;	A
	db	11	;	S
	db	11	;	D
	db	11	;	U
	db	10	;	R
	db	2	;	I
	db	10	;	B
	db	11	;	N
	db	12	;	C
	db	8	;	L
	db	13	;	O
	db	13	;	G
	db	10	;	P
	db	2	;	'
