	;	This file is auto-generated by the LogoCreator program
	;	Created: 25/08/2026 16:54 (UTC)

RoundelRow1
	db	$1d, $76, $03, $fc, $00, $eb, $07, $07, $15
RoundelRow2
	db	$12, $39, $0a, $f3, $05, $c2, $0e, $10, $0a
RoundelRow3
	db	$08, $ec, $18, $15, $0c
RoundelRow4
	db	$0e, $e7, $17, $1a, $02
RoundelRow5
	db	$04, $6a, $1f, $e0, $2e, $cf, $23, $23, $3c
RoundelRow6
	db	$32, $51, $26, $d7, $39, $c4, $2a, $2c, $3a
RoundelRow7
	db	$38, $1c, $31, $ce, $20, $ff, $35, $35, $20
RoundelRow8
	db	$21, $c7, $2d, $3a, $2d
RoundelRow9
	db	$29, $4a, $3f, $c0, $54, $af, $43, $43, $51
RoundelRow10
	db	$51, $57, $46, $b7, $5f, $c2, $4a, $4c, $59
RoundelRow11
	db	$5a, $38, $51, $ae, $44, $bd, $55, $55, $42
RoundelRow12
	db	$44, $49, $58, $a5, $43, $d4, $5c, $5e, $4c
RoundelRow13
	db	$73, $16, $63, $9c, $7c, $8b, $67, $67, $7b
RoundelRow14
	db	$7b, $7b, $6a, $93, $77, $e6, $6e, $70, $63
RoundelRow15
	db	$60, $04, $75, $8a, $6c, $99, $79, $79, $68
RoundelRow16
	db	$6a, $6d, $7c, $81, $63, $08, $80, $82, $92
RoundelRow17
	db	$95, $f2, $87, $78, $94, $67, $8b, $8b, $9d
RoundelRow18
	db	$9c, $71, $91, $90, $80
RoundelRow19
	db	$82, $a0, $95, $6a, $88, $5b, $99, $99, $8a
RoundelRow20
	db	$8b, $eb, $9c, $61, $81, $4e, $a0, $a2, $b3
RoundelRow21
	db	$ab, $b4, $a7, $58, $88, $21, $ab, $ab, $a3
RoundelRow22
	db	$a2, $9d, $ae, $4f, $91, $7e, $b2, $b4, $ba
RoundelRow23
	db	$b9, $c0, $b9, $46, $9a, $55, $bd, $bd, $b1
RoundelRow24
	db	$b1, $d1, $c0, $3d, $e1, $4c, $c4, $c6, $c9
RoundelRow25
	db	$c6, $fa, $cb, $34, $ee, $01, $cf, $cf, $de
RoundelRow26
	db	$df, $a5, $d2, $2b, $f7, $38, $d6, $d8, $d7
RoundelRow27
	db	$d4, $24, $f8, $dd, $d0
RoundelRow28
	db	$d2, $d3, $e0, $1d, $c7, $28, $e4, $e6, $ea
RoundelRow29
	db	$e5, $9e, $eb, $14, $c8, $03, $ef, $ef, $fd
RoundelRow30
	db	$fc, $0d, $d5, $f4, $f8
RoundelRow31
	db	$fa, $e6, $f9, $06, $dc, $73, $fd, $fd, $f2
RoundelRow32
	db	$f3, $33, $00, $fd, $25, $c8, $04, $06, $0b
RoundelRow33
	db	$04, $7e, $0b, $f4, $1c, $f3, $0f, $ff, $14, $e6, $13, $ec, $04, $fb, $17, $17
	db	$14
RoundelRow34
	db	$15, $e5, $0b, $e4, $1c, $ee, $19, $d1, $20, $dd, $33, $24, $29
RoundelRow35
	db	$2d, $36, $29, $d6, $25, $db, $26, $d2, $21, $a7, $31, $31, $39
RoundelRow36
	db	$38, $07, $34, $c9, $39, $c0, $38, $ca, $31, $cd, $3c, $c1, $31, $8c, $40, $42
	db	$48
RoundelRow37
	db	$4f, $32, $47, $b8, $45, $b5, $4b, $bb, $40, $be, $4f, $b0, $5d, $bf, $53, $53
	db	$5f
RoundelRow38
	db	$5e, $a9, $5a, $a6, $58, $aa, $55, $ab, $5c, $a1, $52, $60, $6a
RoundelRow39
	db	$68, $72, $65, $9a, $6b, $97, $78, $96, $67, $e3, $6d, $6d, $64
RoundelRow40
	db	$65, $61, $70, $8d, $7f, $88, $74, $86, $67, $8b, $78, $85, $77, $f4, $7c, $7e
	db	$75
RoundelRow41
	db	$8a, $b2, $83, $7c, $88, $75, $94, $78, $84, $45, $8b, $8b, $86
RoundelRow42
	db	$87, $f9, $8e, $6f, $9a, $6e, $92, $64, $87, $65, $96, $67, $92, $74, $9a, $9c
	db	$97
RoundelRow43
	db	$94, $60, $ac, $51, $b6, $5c, $a8, $a5, $ac
RoundelRow44
	db	$ae, $b9, $a8, $55, $a0, $52, $ac, $5e, $bb, $47, $b0, $4d, $b8, $3c, $b4, $b6
	db	$be
RoundelRow45
	db	$b1, $a8, $bb, $44, $b7, $45, $bf, $4f, $d4, $30, $c3, $3c, $cf, $4d, $c7, $c7
	db	$c1
RoundelRow46
	db	$c0, $f9, $ca, $33, $c6, $3e, $d9, $2f, $da, $1e, $d2, $d4, $dc
RoundelRow47
	db	$df, $a0, $d9, $26, $d0, $27, $dd, $2d, $c8, $2c, $e1, $1e, $e8, $0d, $e5, $e5
	db	$ef
RoundelRow48
	db	$ee, $17, $e2, $12, $ea, $1c, $fb, $1f, $ee, $0f, $fa, $f2, $fa
RoundelRow49
	db	$fd, $0a, $fc, $09, $f9, $09, $e2, $0c, $fd, $02, $f4, $ff, $09
RoundelRow50
	db	$09, $13, $02, $fb, $0f, $fa, $06, $f8, $11, $f9, $0a, $f3, $07, $86, $0e, $10
	db	$19
RoundelRow51
	db	$1a, $20, $15, $ea, $1c, $ef, $19, $e9, $02, $ea, $1d, $e2, $14, $d3, $21, $21
	db	$2a
RoundelRow52
	db	$2b, $17, $24, $d9, $2d, $d8, $33, $d5, $21, $e0, $2c, $2e, $27
RoundelRow53
	db	$38, $46, $33, $cc, $3d, $cb, $37, $c7, $22, $ce, $3b, $c4, $35, $d3, $3f, $3f
	db	$48
RoundelRow54
	db	$49, $bd, $49, $bc, $44, $b6, $5d, $b9, $48, $b5, $41, $4c, $45
RoundelRow55
	db	$46, $b0, $5a, $a1, $4e, $ac, $5e, $55, $5e
RoundelRow56
	db	$50, $49, $58, $a5, $52, $a2, $5c, $ae, $43, $97, $60, $9d, $6a, $ec, $64, $66
	db	$60
RoundelRow57
	db	$6f, $78, $6b, $94, $65, $91, $6f, $9f, $6c, $82, $73, $8c, $7d, $fd, $77, $77
	db	$7f
RoundelRow58
	db	$7e, $49, $7a, $83, $74, $86, $7e, $70, $9d, $73, $82, $7b, $8c, $4a, $86, $88
	db	$8e
RoundelRow59
	db	$8d, $b8, $8d, $72, $87, $77, $91, $61, $8e, $62, $95, $6a, $9f, $5b, $99, $99
	db	$9d
RoundelRow60
	db	$9c, $eb, $9c, $61, $96, $50, $bf, $5d, $aa, $4a, $a4, $a6, $a0
RoundelRow61
	db	$af, $de, $ab, $54, $a4, $53, $af, $5f, $ae, $46, $b3, $4c, $bc, $5b, $b7, $b7
	db	$bf
RoundelRow62
	db	$be, $45, $b2, $40, $bc, $4e, $a1, $33, $c0, $3d, $ca, $c4, $c2
RoundelRow63
	db	$c1, $38, $c1, $31, $cb, $3b, $d2, $3c, $cf, $30, $d9, $d1, $d5
RoundelRow64
	db	$d5, $c5, $d4, $29, $de, $28, $f9, $25, $d2, $54, $dc, $de, $d9
RoundelRow65
	db	$e6, $f0, $e3, $1c, $ed, $15, $c6, $18, $e1, $61, $eb, $eb, $ea
RoundelRow66
	db	$eb, $dd, $ee, $0f, $f9, $0c, $f2, $04, $d5, $01, $f6, $07, $f1, $36, $fa, $fc
	db	$fb
RoundelRow67
	db	$f8, $cc, $01, $fe, $0a, $ff, $05, $f5, $26, $f4, $09, $f6, $02, $c7, $0d, $0d
	db	$08
RoundelRow68
	db	$09, $67, $10, $ed, $1b, $e8, $14, $e6, $37, $eb, $18, $e5, $13, $f2, $1c, $1e
	db	$19
RoundelRow69
	db	$26, $56, $23, $dc, $2c, $dd, $27, $d7, $08, $d8, $2b, $d4, $24, $c3, $2f, $2f
	db	$36
RoundelRow70
	db	$37, $cd, $3a, $c4, $17, $c9, $3e, $38, $3f
RoundelRow71
	db	$3c, $c4, $35, $cd, $1c, $c0, $49, $41, $44
RoundelRow72
	db	$45, $bb, $4d, $b8, $46, $b8, $6b, $bd, $4a, $b3, $45, $4e, $49
RoundelRow73
	db	$55, $40, $53, $ac, $5c, $a9, $57, $a7, $7a, $aa, $5b, $a4, $54, $d5, $5f, $5f
	db	$65
RoundelRow74
	db	$64, $73, $62, $9b, $6d, $9a, $66, $98, $4b, $99, $6a, $93, $65, $e6, $6e, $70
	db	$74
RoundelRow75
	db	$77, $40, $75, $8a, $7e, $8f, $79, $89, $58, $8a, $7d, $82, $76, $b3, $81, $81
	db	$87
RoundelRow76
	db	$86, $b7, $84, $79, $8f, $70, $88, $7a, $a9, $7d, $8c, $71, $87, $5c, $90, $92
	db	$96
RoundelRow77
	db	$91, $a6, $97, $68, $90, $69, $be, $64, $94, $51, $9f, $9f, $a5
RoundelRow78
	db	$a4, $d5, $a2, $5b, $ad, $56, $83, $57, $a1, $44, $aa, $ac, $a8
RoundelRow79
	db	$ab, $d8, $b1, $4e, $b5, $4d, $b5, $45, $92, $40, $b9, $46, $bd, $55, $bd, $bd
	db	$bb
RoundelRow80
	db	$ba, $b7, $c0, $3d, $c4, $3a, $c4, $36, $e3, $3f, $c8, $35, $cc, $22, $cc, $ce
	db	$ca
RoundelRow81
	db	$d5, $a6, $d3, $2c, $d3, $29, $d7, $27, $fc, $2a, $db, $24, $db, $33, $df, $df
	db	$e5
RoundelRow82
	db	$e4, $1d, $eb, $18, $e4, $16, $c3, $1b, $e8, $15, $e3, $ec, $e8
RoundelRow83
	db	$eb, $10, $f8, $0d, $f3, $03, $d0, $06, $f7, $08, $f0, $f9, $ff
RoundelRow84
	db	$fe, $03, $f5, $06, $fe, $f0, $25, $f3, $02, $fb, $0d, $06, $02
RoundelRow85
	db	$0c, $18, $0b, $f4, $04, $f5, $0f, $ff, $34, $e0, $13, $ec, $1c, $9d, $17, $17
	db	$1c
RoundelRow86
	db	$1d, $0b, $1a, $e3, $15, $e6, $1e, $d0, $05, $d3, $22, $db, $2d, $ae, $26, $28
	db	$2d
RoundelRow87
	db	$2e, $3a, $2d, $d2, $26, $df, $16, $ce, $3a, $bb, $35, $35, $32
RoundelRow88
	db	$33, $29, $38, $c5, $33, $cc, $1b, $c1, $37, $c8, $40, $42, $47
RoundelRow89
	db	$40, $76, $47, $b8, $40, $b9, $6c, $b4, $44, $81, $4f, $4f, $54
RoundelRow90
	db	$55, $61, $52, $ab, $52, $a8, $56, $a8, $7f, $ad, $5a, $a3, $5a, $92, $5e, $60
	db	$65
RoundelRow91
	db	$66, $50, $65, $9a, $61, $99, $69, $99, $4c, $9c, $6d, $92, $69, $a3, $71, $71
	db	$76
RoundelRow92
	db	$77, $47, $74, $89, $70, $86, $78, $8a, $5d, $8b, $7c, $81, $78, $4c, $80, $82
	db	$87
RoundelRow93
	db	$80, $b6, $87, $78, $8f, $75, $8b, $7b, $aa, $7e, $8f, $70, $97, $5d, $93, $93
	db	$90
RoundelRow94
	db	$91, $a5, $96, $67, $9e, $66, $9a, $6c, $bb, $6d, $9e, $5f, $a6, $6e, $a2, $a4
	db	$a1
RoundelRow95
	db	$a2, $d0, $a9, $56, $ad, $57, $ad, $5d, $88, $5c, $b1, $4e, $b5, $5d, $b5, $b5
	db	$b2
RoundelRow96
	db	$b3, $cf, $b8, $45, $bc, $40, $bc, $4e, $99, $33, $c0, $3d, $c4, $2a, $c4, $c6
	db	$c3
RoundelRow97
	db	$cc, $be, $cb, $34, $cb, $31, $cf, $3f, $f6, $22, $d3, $2c, $d3, $3b, $d7, $d7
	db	$dc
RoundelRow98
	db	$dd, $ad, $da, $23, $da, $26, $de, $10, $c7, $13, $e2, $1b, $e2, $08, $e6, $e8
	db	$ed
RoundelRow99
	db	$ee, $9c, $ed, $12, $e9, $17, $f1, $01, $d4, $02, $f5, $0a, $f1, $19, $f9, $f9
	db	$fe
RoundelRow100
	db	$ff, $8b, $fc, $01, $f8, $f8, $00, $f2, $25, $f5, $04, $f9, $00, $e6, $08, $0a
	db	$0f
RoundelRow101
	db	$08, $7a, $0f, $f0, $17, $e9, $13, $e3, $32, $e4, $17, $e8, $1f, $f7, $1b, $1b
	db	$18
RoundelRow102
	db	$19, $e1, $17, $d8, $20, $d2, $05, $d5, $24, $d9, $2f, $28, $2d
RoundelRow103
	db	$2e, $d4, $24, $d5, $2f, $df, $16, $c0, $33, $cc, $3c, $35, $32
RoundelRow104
	db	$33, $c7, $31, $ca, $13, $c3, $35, $3e, $3b
RoundelRow105
	db	$44, $be, $4a, $b3, $6c, $ba, $4e, $47, $4c
RoundelRow106
	db	$4d, $b5, $43, $bc, $65, $b1, $47, $50, $55
RoundelRow107
	db	$56, $ac, $5c, $a5, $7e, $a8, $50, $59, $5e
RoundelRow108
	db	$5f, $a3, $55, $ae, $77, $9f, $69, $62, $67
RoundelRow109
	db	$60, $9a, $6e, $97, $40, $96, $62, $6b, $68
RoundelRow110
	db	$69, $91, $67, $80, $59, $8d, $7b, $74, $71
RoundelRow111
	db	$72, $88, $70, $89, $52, $84, $74, $7d, $7a
RoundelRow112
	db	$7b, $7f, $89, $72, $ab, $7b, $8d, $86, $83

RoundelRowList
	dw	RoundelRow1
	dw	RoundelRow2
	dw	RoundelRow3
	dw	RoundelRow4
	dw	RoundelRow5
	dw	RoundelRow6
	dw	RoundelRow7
	dw	RoundelRow8
	dw	RoundelRow9
	dw	RoundelRow10
	dw	RoundelRow11
	dw	RoundelRow12
	dw	RoundelRow13
	dw	RoundelRow14
	dw	RoundelRow15
	dw	RoundelRow16
	dw	RoundelRow17
	dw	RoundelRow18
	dw	RoundelRow19
	dw	RoundelRow20
	dw	RoundelRow21
	dw	RoundelRow22
	dw	RoundelRow23
	dw	RoundelRow24
	dw	RoundelRow25
	dw	RoundelRow26
	dw	RoundelRow27
	dw	RoundelRow28
	dw	RoundelRow29
	dw	RoundelRow30
	dw	RoundelRow31
	dw	RoundelRow32
	dw	RoundelRow33
	dw	RoundelRow34
	dw	RoundelRow35
	dw	RoundelRow36
	dw	RoundelRow37
	dw	RoundelRow38
	dw	RoundelRow39
	dw	RoundelRow40
	dw	RoundelRow41
	dw	RoundelRow42
	dw	RoundelRow43
	dw	RoundelRow44
	dw	RoundelRow45
	dw	RoundelRow46
	dw	RoundelRow47
	dw	RoundelRow48
	dw	RoundelRow49
	dw	RoundelRow50
	dw	RoundelRow51
	dw	RoundelRow52
	dw	RoundelRow53
	dw	RoundelRow54
	dw	RoundelRow55
	dw	RoundelRow56
	dw	RoundelRow57
	dw	RoundelRow58
	dw	RoundelRow59
	dw	RoundelRow60
	dw	RoundelRow61
	dw	RoundelRow62
	dw	RoundelRow63
	dw	RoundelRow64
	dw	RoundelRow65
	dw	RoundelRow66
	dw	RoundelRow67
	dw	RoundelRow68
	dw	RoundelRow69
	dw	RoundelRow70
	dw	RoundelRow71
	dw	RoundelRow72
	dw	RoundelRow73
	dw	RoundelRow74
	dw	RoundelRow75
	dw	RoundelRow76
	dw	RoundelRow77
	dw	RoundelRow78
	dw	RoundelRow79
	dw	RoundelRow80
	dw	RoundelRow81
	dw	RoundelRow82
	dw	RoundelRow83
	dw	RoundelRow84
	dw	RoundelRow85
	dw	RoundelRow86
	dw	RoundelRow87
	dw	RoundelRow88
	dw	RoundelRow89
	dw	RoundelRow90
	dw	RoundelRow91
	dw	RoundelRow92
	dw	RoundelRow93
	dw	RoundelRow94
	dw	RoundelRow95
	dw	RoundelRow96
	dw	RoundelRow97
	dw	RoundelRow98
	dw	RoundelRow99
	dw	RoundelRow100
	dw	RoundelRow101
	dw	RoundelRow102
	dw	RoundelRow103
	dw	RoundelRow104
	dw	RoundelRow105
	dw	RoundelRow106
	dw	RoundelRow107
	dw	RoundelRow108
	dw	RoundelRow109
	dw	RoundelRow110
	dw	RoundelRow111
	dw	RoundelRow112
