ZP_TEXT_DRAW_LENGTH
ZP_SCREEN_DRAW_PIXEL_ROW
	db	0

ZP_TEXT_DRAW_CURRENT_X
ZP_SCREEN_DRAW_RLE_BYTE
	db	0

ZP_TEXT_DRAW_PIXEL_INDEX
ZP_SCREEN_DRAW_RLE_COUNT_REMAINING
	db	0

ZP_TEXT_DRAW_CHARACTER_COLUMNS_REMAINING
ZP_SCREEN_DRAW_COUNT_REMAINING
	db	0

ZP_INTRO_SCREEN_DRAW_TYPE
	db	0

ZP_TEXT_DRAW_COLUMN_AND_VALUE
ZP_RED_BAR_X_START
	db	0
ZP_TEXT_DRAW_COLUMN_OR_VALUE
ZP_RED_BAR_X_END
	db	0
ZP_RED_BAR_X_START_INDEX
	db	0
ZP_RED_BAR_X_END_INDEX
	db	0

ZP_TRANSFER_HOST_TUBE_HANDLER_POINTER_SRC	;	2 bytes
ZP_TEXT_DRAW_OUTPUT_ADDRESS	;	2 bytes
ZP_SCREEN_DRAW_OUTPUT_POINTER	;	2 bytes
	dw	0

ZP_TRANSFER_HOST_TUBE_HANDLER_POINTER_DEST	;	2 bytes
ZP_TEXT_DRAW_INPUT_ADDRESS	;	2 bytes
ZP_SCREEN_DRAW_INPUT_POINTER	;	2 bytes
	dw	0

ZP_TRANSFER_HOST_TUBE_HANDLER_COUNTER	;	2 bytes
ZP_TEXT_DRAW_STRING_ADDRESS	;	2 bytes
	dw	0

ZP_TEXT_DRAW_CURRENT_COLUMN_PIXELS
	dw	0
