	;	this file is for game-specific address definitions

BOOT_START_ADDRESS		equ	$2000
BOOT_ZP_ADDRESS_START		equ	$70
BOOT_ZP_ADDRESS_END		equ	$8f

BREAK_INTERCEPT_START_ADDRESS	equ	$130

HOST_TUBE_START_ADDRESS		equ	$400
HOST_TUBE_ZP_ADDRESS_START	equ	0
