	;	this file is for Beeb OS definitions, a fair amount of
	;	which will probably not be used

OSWRSC	equ	$ffb3
OSRDSC	equ	$ffb9
OSRDRM	equ	$ffb9
OSEVEN	equ	$ffbf
GSINIT	equ	$ffc2
GSREAD	equ	$ffc5
NVRDCH	equ	$ffc8
NVWRCH	equ	$ffcb
OSFIND	equ	$ffce
OSGBPB	equ	$ffd1
OSBPUT	equ	$ffd4
OSBGET	equ	$ffd7
OSARGS	equ	$ffda
OSFILE	equ	$ffdd
OSRDCH	equ	$ffe0
OSASCI	equ	$ffe3
OSNEWL	equ	$ffe7
OSWRCH	equ	$ffee
OSWORD	equ	$fff1
OSBYTE	equ	$fff4
OSCLI		equ	$fff7

VDU_WRITE_TEXT_AT_TEXT_CURSOR		equ	4
VDU_WRITE_TEXT_AT_GRAPHICS_CURSOR	equ	5
VDU_ENABLE_VDU				equ	6
VDU_CLEAR_SCREEN				equ	12
VDU_DEFINE_TEXT_COLOUR			equ	17
VDU_DEFINE_GRAPHICS_COLOUR		equ	18
VDU_CHANGE_PALETTE			equ	19
VDU_DISABLE_VDU				equ	21
VDU_CHANGE_MODE				equ	22
VDU_PLOT					equ	25
VDU_RESET_TEXT_WINDOW			equ	26
VDU_DEFINE_TEXT_WINDOW			equ	28
VDU_DEFINE_GRAPHICS_ORIGIN		equ	29
VDU_MOVE_TEXT_CURSOR			equ	31

OS_BREAK_INTERCEPT	equ	$287

SHEILA			equ	$fe00

CRTC_BASE_ADDRESS	equ	SHEILA
CRTC_ADDRESS_REGISTER	equ	CRTC_BASE_ADDRESS + $00
CRTC_VALUE_REGISTER	equ	CRTC_BASE_ADDRESS + $01

CRTC_INTERLACE_DELAY_DISABLE_CURSOR_OFF	equ	$c0
CRTC_INTERLACE_DELAY_DISABLE_CURSOR_ON	equ	0
CRTC_INTERLACE_DELAY_DISABLE_DISPLAY_OFF	equ	$30
CRTC_INTERLACE_DELAY_DISABLE_DISPLAY_ON	equ	0

VIDEO_ULA_CONTROL_REGISTER	equ	SHEILA + $20
VIDEO_ULA_PALETTE_REGISTER	equ	SHEILA + $21

VIDEO_NULA_CONTROL_REGISTER	equ	SHEILA + $22
VIDEO_NULA_PALETTE_REGISTER	equ	SHEILA + $23

SYSTEM_VIA_BASE		equ	SHEILA + $40
SYSTEM_VIA_PORT_B		equ	SYSTEM_VIA_BASE + $0
SYSTEM_VIA_PORT_A		equ	SYSTEM_VIA_BASE + $1
SYSTEM_VIA_DDRB		equ	SYSTEM_VIA_BASE + $2
SYSTEM_VIA_DDRA		equ	SYSTEM_VIA_BASE + $3
SYSTEM_VIA_T1C_L		equ	SYSTEM_VIA_BASE + $4
SYSTEM_VIA_T1C_H		equ	SYSTEM_VIA_BASE + $5
SYSTEM_VIA_T1L_L		equ	SYSTEM_VIA_BASE + $6
SYSTEM_VIA_T1L_H		equ	SYSTEM_VIA_BASE + $7
SYSTEM_VIA_T2C_L		equ	SYSTEM_VIA_BASE + $8
SYSTEM_VIA_T2C_H		equ	SYSTEM_VIA_BASE + $9
SYSTEM_VIA_SR		equ	SYSTEM_VIA_BASE + $a
SYSTEM_VIA_ACR		equ	SYSTEM_VIA_BASE + $b
SYSTEM_VIA_PCR		equ	SYSTEM_VIA_BASE + $c
SYSTEM_VIA_IFR		equ	SYSTEM_VIA_BASE + $d
SYSTEM_VIA_IER		equ	SYSTEM_VIA_BASE + $e
SYSTEM_VIA_PORT_A_NH	equ	SYSTEM_VIA_BASE + $f

SYSTEM_VIA_STATUS_KEYPRESS	equ	1
SYSTEM_VIA_STATUS_VSYNC		equ	2
SYSTEM_VIA_STATUS_SHIFT_REG	equ	4
SYSTEM_VIA_STATUS_LIGHTPEN	equ	8
SYSTEM_VIA_STATUS_ADC		equ	$10
SYSTEM_VIA_STATUS_SPEECH	equ	$20
SYSTEM_VIA_STATUS_100HZ		equ	$40
SYSTEM_VIA_STATUS_WAS_ME	equ	$80

USER_VIA_BASE	equ	SHEILA + $60
USER_VIA_PORT_B	equ	USER_VIA_BASE + $0
USER_VIA_DDR_B	equ	USER_VIA_BASE + $2
USER_VIA_T1C_L	equ	USER_VIA_BASE + $4
USER_VIA_T1C_H	equ	USER_VIA_BASE + $5
USER_VIA_T1L_L	equ	USER_VIA_BASE + $6
USER_VIA_T1L_H	equ	USER_VIA_BASE + $7
USER_VIA_T2LC_L	equ	USER_VIA_BASE + $8
USER_VIA_T2LC_H	equ	USER_VIA_BASE + $9
USER_VIA_ACR	equ	USER_VIA_BASE + $b
USER_VIA_PCR	equ	USER_VIA_BASE + $c
USER_VIA_IFR	equ	USER_VIA_BASE + $d
USER_VIA_IER	equ	USER_VIA_BASE + $e

USER_VIA_IFR_FLAG_TIMER_2	equ	$20
USER_VIA_IFR_FLAG_TIMER_1	equ	$40

CRTC_REGISTER_HORIZONTAL_TOTAL		equ	$0
CRTC_REGISTER_HORIZONTAL_DISPLAYED		equ	$1
CRTC_REGISTER_HORIZONTAL_SYNC_POSITION	equ	$2
CRTC_REGISTER_SYNC_WIDTH			equ	$3
CRTC_REGISTER_VERTICAL_TOTAL			equ	$4
CRTC_REGISTER_VERTICAL_TOTAL_ADJUST		equ	$5
CRTC_REGISTER_VERTICAL_DISPLAYED		equ	$6
CRTC_REGISTER_VERTICAL_SYNC_POSITION	equ	$7
CRTC_REGISTER_INTERLACE_DELAY_DISABLE	equ	$8
CRTC_REGISTER_SCAN_LINES_PER_CHARACTER	equ	$9
CRTC_REGISTER_CURSOR_START			equ	$a
CRTC_REGISTER_CURSOR_END			equ	$b
CRTC_REGISTER_SCREEN_START_H			equ	$c
CRTC_REGISTER_SCREEN_START_L			equ	$d
CRTC_REGISTER_CURSOR_POSITION_H		equ	$e
CRTC_REGISTER_CURSOR_POSITION_L		equ	$f

OSBYTE_READ_OS_VERSION_NUMBER							equ	$00
OSBYTE_ENABLE_DISABLE_CURSOR_EDITING					equ	$04
OSBYTE_SET_FLASHING_COLOURS_MARK_DURATION					equ	$09
OSBYTE_DISABLE_EVENT                 					equ	$0d
OSBYTE_ENABLE_EVENT                 					equ	$0e
OSBYTE_WAIT_FOR_VERTICAL_SYNC							equ	$13
OSBYTE_EXPLODE_CHARACTER_DEFINITION_RAM					equ	$14
OSBYTE_FLUSH_SPECIFIC_BUFFER							equ	$15
OSBYTE_KEYBOARD_SCAN_FROM_16							equ	$7a
OSBYTE_READ_KEY_WITH_TIME_LIMIT						equ	$81
OSBYTE_SELECT_FILE_OPTIONS							equ	$8b
OSBYTE_SELECT_TAPE_FILING_SYSTEM						equ	$8c
OSBYTE_ENTER_LANGUAGE_ROM							equ	$8e
OSBYTE_ISSUE_PAGED_ROM_SERVICE_REQUEST					equ	$8f
OSBYTE_INSERT_CHARACTER_INTO_INPUT_BUFFER_CHECKING_FOR_ESCAPE	equ	$99
OSBYTE_READ_WRITE_ACIA_CONTROL_REGSTER_AND_RAM_COPY			equ	$9c
	;	Master series
OSBYTE_READ_CMOS_RAM_OR_EEPROM						equ	$a1
OSBYTE_WRITE_CMOS_RAM_OR_EEPROM						equ	$a2
	;	system variables
OSBYTE_READ_KEYBOARD_TRANSLATION_TABLE_ADDRESS				equ	$ac
OSBYTE_READ_VIDEO_ULA_CONTROL_REGISTER_RAM_COPY				equ	$b8
OSBYTE_READ_ACIA_CONTROL_REGSTER_RAM_COPY					equ	$c0
OSBYTE_READ_WRITE_FLASH_COUNTER						equ	$c1
OSBYTE_READ_WRITE_BREAK_ESCAPE_EFFECT					equ	$c8
OSBYTE_READ_WRITE_SOUND_SUPPRESSION_STATUS				equ	$d2
OSBYTE_READ_WRITE_TUBE_PRESENCE_FLAG					equ	$ea
OSBYTE_READ_WRITE_SPEECH_PRESENCE_FLAG					equ	$eb
OSBYTE_READ_WRITE_CURSOR_EDITING_STATUS					equ	$ed
OSBYTE_READ_WRITE_SERIAL_ULA_RAM_COPY					equ	$f2
OSBYTE_READ_WRITE_CURRENT_LANGUAGE_ROM_NUMBER				equ	$fc
OSBYTE_READ_LAST_BREAK_TYPE							equ	$fd
OSBYTE_READ_WRITE_AVAILABLE_RAM						equ	$fe
OSBYTE_READ_WRITE_START_UP_OPTIONS						equ	$ff

OSBYTE_SYSTEM_VARIABLES_BASE							equ	$a6

OSWORD_PLAY_SOUND		equ	7
OSWORD_SET_ENVELOPE	equ	8

USERV		equ	$200
BRKV		equ	$202
IRQ1V		equ	$204
IRQ2V		equ	$206
CLIV		equ	$208
BYTEV		equ	$20a
WORDV		equ	$20c
WRCHV		equ	$20e
RDCHV		equ	$210
FILEV		equ	$212
ARGSV		equ	$214
BGETV		equ	$216
BPUTV		equ	$218
GBPBV		equ	$21a
FINDV		equ	$21c
FSCV		equ	$21e
EVNTV		equ	$220
UPTV		equ	$222
NETV		equ	$224
VDUV		equ	$226
KEYV		equ	$228
INSV		equ	$22a
REMV		equ	$22c
CNPV		equ	$22e
IND1V		equ	$230
IND2V		equ	$232
IND3V		equ	$234

IRQBRKV	equ	$fffe
RESETV	equ	$fffc
NMIV		equ	$fffa
	;	65816 emulation mode vectors
ABORTV	equ	$fff8
COPV		equ	$fff4
	;	65816 native mode vectors
NIRQV		equ	$ffee
NNMIV		equ	$ffea
NABORTV	equ	$ffe8
NBRKV		equ	$ffe6
NCOPV		equ	$ffe4

COLOUR_BLACK	equ	0
COLOUR_RED		equ	1
COLOUR_GREEN	equ	2
COLOUR_YELLOW	equ	3
COLOUR_BLUE		equ	4
COLOUR_MAGENTA	equ	5
COLOUR_CYAN		equ	6
COLOUR_WHITE	equ	7

TELETEXT_TEXT_RED			equ	$81
TELETEXT_TEXT_GREEN		equ	$82
TELETEXT_TEXT_YELLOW		equ	$83
TELETEXT_TEXT_BLUE		equ	$84
TELETEXT_TEXT_MAGENTA		equ	$85
TELETEXT_TEXT_CYAN		equ	$86
TELETEXT_TEXT_WHITE		equ	$87
TELETEXT_FLASHING			equ	$88
TELETEXT_STEADY			equ	$89
TELETEXT_NORMAL_HEIGHT		equ	$8c
TELETEXT_DOUBLE_HEIGHT		equ	$8d
TELETEXT_GRAPHICS_RED		equ	$91
TELETEXT_GRAPHICS_GREEN		equ	$92
TELETEXT_GRAPHICS_YELLOW	equ	$93
TELETEXT_GRAPHICS_BLUE		equ	$94
TELETEXT_GRAPHICS_MAGENTA	equ	$95
TELETEXT_GRAPHICS_CYAN		equ	$96
TELETEXT_GRAPHICS_WHITE		equ	$97
TELETEXT_CONCEAL			equ	$98
TELETEXT_SOLID_GRAPHICS		equ	$99
TELETEXT_SEPARATED_GRAPHICS	equ	$9a
TELETEXT_BLACK_BACKGROUND	equ	$9c
TELETEXT_NEW_BACKGROUND		equ	$9d
TELETEXT_HOLD_GRAPHICS		equ	$9e
TELETEXT_RELEASE_GRAPHICS	equ	$9f

TELETEXT_SEGMENTS_BASE		equ	$a0
TELETEXT_SEGMENT_TOP_LEFT	equ	1
TELETEXT_SEGMENT_TOP_RIGHT	equ	2
TELETEXT_SEGMENT_MIDDLE_LEFT	equ	4
TELETEXT_SEGMENT_MIDDLE_RIGHT	equ	8
TELETEXT_SEGMENT_BOTTOM_LEFT	equ	$10
TELETEXT_SEGMENT_BOTTOM_RIGHT	equ	$40

TUBE_BASE_ADDRESS_HOST			equ	$fee0
TUBE_STATUS_REGISTER_1_HOST		equ	TUBE_BASE_ADDRESS_HOST
TUBE_DATA_REGISTER_1_HOST		equ	TUBE_BASE_ADDRESS_HOST + 1
TUBE_STATUS_REGISTER_2_HOST		equ	TUBE_BASE_ADDRESS_HOST + 2
TUBE_DATA_REGISTER_2_HOST		equ	TUBE_BASE_ADDRESS_HOST + 3
TUBE_STATUS_REGISTER_3_HOST		equ	TUBE_BASE_ADDRESS_HOST + 4
TUBE_DATA_REGISTER_3_HOST		equ	TUBE_BASE_ADDRESS_HOST + 5
TUBE_STATUS_REGISTER_4_HOST		equ	TUBE_BASE_ADDRESS_HOST + 6
TUBE_DATA_REGISTER_4_HOST		equ	TUBE_BASE_ADDRESS_HOST + 7

TUBE_BASE_ADDRESS_PARASITE		equ	$fef8
	;	some copros use extra bytes for additional control
TUBE_BASE_ADDRESS_PARASITE_EX		equ	$fef0
TUBE_STATUS_REGISTER_1_PARASITE	equ	TUBE_BASE_ADDRESS_PARASITE
TUBE_DATA_REGISTER_1_PARASITE		equ	TUBE_BASE_ADDRESS_PARASITE + 1
TUBE_STATUS_REGISTER_2_PARASITE	equ	TUBE_BASE_ADDRESS_PARASITE + 2
TUBE_DATA_REGISTER_2_PARASITE		equ	TUBE_BASE_ADDRESS_PARASITE + 3
TUBE_STATUS_REGISTER_3_PARASITE	equ	TUBE_BASE_ADDRESS_PARASITE + 4
TUBE_DATA_REGISTER_3_PARASITE		equ	TUBE_BASE_ADDRESS_PARASITE + 5
TUBE_STATUS_REGISTER_4_PARASITE	equ	TUBE_BASE_ADDRESS_PARASITE + 6
TUBE_DATA_REGISTER_4_PARASITE		equ	TUBE_BASE_ADDRESS_PARASITE + 7

TUBE_LATCH_SET				equ	$80
TUBE_LATCH_RESET				equ	$00

TUBE_STATUS_REGISTER_1_FLAG_DA	equ	$80
TUBE_STATUS_REGISTER_1_FLAG_NF	equ	$40
TUBE_STATUS_REGISTER_1_FLAG_P		equ	$20
TUBE_STATUS_REGISTER_1_FLAG_V		equ	$10
TUBE_STATUS_REGISTER_1_FLAG_M		equ	$8
TUBE_STATUS_REGISTER_1_FLAG_J		equ	$4
TUBE_STATUS_REGISTER_1_FLAG_I		equ	$2
TUBE_STATUS_REGISTER_1_FLAG_Q		equ	$1

TUBE_STATUS_REGISTER_1_FLAG_CLEAR_REGISTERS	equ	$40
TUBE_STATUS_REGISTER_1_FLAG_RESET			equ	$20
TUBE_STATUS_REGISTER_1_FLAG_2_BYTE_R3		equ	$10
TUBE_STATUS_REGISTER_1_FLAG_PARASITE_NMI_R3	equ	$8
TUBE_STATUS_REGISTER_1_FLAG_PARASITE_IRQ_R4	equ	$4
TUBE_STATUS_REGISTER_1_FLAG_PARASITE_IRQ_R1	equ	$2
TUBE_STATUS_REGISTER_1_FLAG_HOST_IRQ_R4		equ	$1

TUBE_STATUS_REGISTER_2_FLAG_DA	equ	$80
TUBE_STATUS_REGISTER_2_FLAG_NF	equ	$40

TUBE_STATUS_REGISTER_3_FLAG_DA	equ	$80
TUBE_STATUS_REGISTER_3_FLAG_NF	equ	$40

TUBE_STATUS_REGISTER_4_FLAG_DA	equ	$80
TUBE_STATUS_REGISTER_4_FLAG_NF	equ	$40

TUBE_ACTION_CLAIM					equ	$c0
TUBE_ACTION_RELEASE				equ	$80
TUBE_ACTION_TRANSFER_BYTES_TO_HOST		equ	0
TUBE_ACTION_TRANSFER_BYTES_TO_PARASITE	equ	1
TUBE_ACTION_TRANSFER_WORDS_TO_HOST		equ	2
TUBE_ACTION_TRANSFER_WORDS_TO_PARASITE	equ	3
TUBE_ACTION_EXECUTE_IN_PARASITE		equ	4
TUBE_ACTION_RELEASE_TUBE			equ	5
TUBE_ACTION_TRANSFER_256_TO_HOST		equ	6
TUBE_ACTION_TRANSFER_256_TO_PARASITE	equ	7

TUBE_CUSTOM_CLAIM_ID	equ	$12

TUBE_ENTRY_POINT_GENERAL_PURPOSE	equ	$406

INKEY_VALUE_SPACE		equ	$9d
INKEY_VALUE_COMMA		equ	$99
INKEY_VALUE_MINUS		equ	$e8
INKEY_VALUE_DOT		equ	$98
INKEY_VALUE_SLASH		equ	$97
INKEY_VALUE_0		equ	$d8
INKEY_VALUE_1		equ	$cf
INKEY_VALUE_2		equ	$ce
INKEY_VALUE_3		equ	$ee
INKEY_VALUE_4		equ	$ed
INKEY_VALUE_5		equ	$ec
INKEY_VALUE_6		equ	$cb
INKEY_VALUE_7		equ	$db
INKEY_VALUE_8		equ	$ea
INKEY_VALUE_9		equ	$d9
INKEY_VALUE_COLON		equ	$b7
INKEY_VALUE_SEMI_COLON	equ	$a8
INKEY_VALUE_AT		equ	$b8
INKEY_VALUE_A		equ	$be
INKEY_VALUE_B		equ	$9b
INKEY_VALUE_C		equ	$ad
INKEY_VALUE_D		equ	$cd
INKEY_VALUE_E		equ	$dd
INKEY_VALUE_F		equ	$bc
INKEY_VALUE_G		equ	$ac
INKEY_VALUE_H		equ	$ab
INKEY_VALUE_I		equ	$da
INKEY_VALUE_J		equ	$ba
INKEY_VALUE_K		equ	$b9
INKEY_VALUE_L		equ	$a9
INKEY_VALUE_M		equ	$9a
INKEY_VALUE_N		equ	$aa
INKEY_VALUE_O		equ	$c9
INKEY_VALUE_P		equ	$c8
INKEY_VALUE_Q		equ	$ef
INKEY_VALUE_R		equ	$cc
INKEY_VALUE_S		equ	$ae
INKEY_VALUE_T		equ	$dc
INKEY_VALUE_U		equ	$ca
INKEY_VALUE_V		equ	$9c
INKEY_VALUE_W		equ	$de
INKEY_VALUE_X		equ	$bd
INKEY_VALUE_Y		equ	$bb
INKEY_VALUE_Z		equ	$9e
INKEY_VALUE_LEFT_SQ	equ	$c7
INKEY_VALUE_BACKSLASH	equ	$87
INKEY_VALUE_RIGHT_SQ	equ	$a7
INKEY_VALUE_HAT		equ	$e7
INKEY_VALUE_UNDERSCORE	equ	$d7
INKEY_VALUE_ESCAPE	equ	$8f
INKEY_VALUE_TAB		equ	$9f
INKEY_VALUE_CAPS_LOCK	equ	$bf
INKEY_VALUE_CTRL		equ	$fe
INKEY_VALUE_SHIFT_LOCK	equ	$af
INKEY_VALUE_SHIFT		equ	$ff
INKEY_VALUE_DELETE	equ	$a6
INKEY_VALUE_COPY		equ	$96
INKEY_VALUE_RETURN	equ	$b6
INKEY_VALUE_UP_ARROW	equ	$c6
INKEY_VALUE_DOWN_ARROW	equ	$d6
INKEY_VALUE_LEFT_ARROW	equ	$e6
INKEY_VALUE_RIGHT_ARROW	equ	$86
INKEY_VALUE_F0		equ	$df
INKEY_VALUE_F1		equ	$8e
INKEY_VALUE_F2		equ	$8d
INKEY_VALUE_F3		equ	$8c
INKEY_VALUE_F4		equ	$eb
INKEY_VALUE_F5		equ	$8b
INKEY_VALUE_F6		equ	$8a
INKEY_VALUE_F7		equ	$e9
INKEY_VALUE_F8		equ	$89
INKEY_VALUE_F9		equ	$88
	;	Master only
INKEY_VALUE_KEYPAD_0		equ	$95
INKEY_VALUE_KEYPAD_1		equ	$94
INKEY_VALUE_KEYPAD_2		equ	$83
INKEY_VALUE_KEYPAD_3		equ	$93
INKEY_VALUE_KEYPAD_4		equ	$85
INKEY_VALUE_KEYPAD_5		equ	$84
INKEY_VALUE_KEYPAD_6		equ	$e5
INKEY_VALUE_KEYPAD_7		equ	$e4
INKEY_VALUE_KEYPAD_8		equ	$d5
INKEY_VALUE_KEYPAD_9		equ	$d4
INKEY_VALUE_KEYPAD_PLUS		equ	$c5
INKEY_VALUE_KEYPAD_MINUS	equ	$c4
INKEY_VALUE_KEYPAD_DIVIDE	equ	$b5
INKEY_VALUE_KEYPAD_HASH		equ	$a5
INKEY_VALUE_KEYPAD_STAR		equ	$a4
INKEY_VALUE_KEYPAD_COMMA	equ	$a3
INKEY_VALUE_KEYPAD_DOT		equ	$b3
INKEY_VALUE_KEYPAD_RETURN	equ	$c3
INKEY_VALUE_KEYPAD_DELETE	equ	$b4

ADDRESSABLE_LATCH_BIT_WRITE_SOUND		equ	0
ADDRESSABLE_LATCH_BIT_READ_SPEECH		equ	1
ADDRESSABLE_LATCH_BIT_WRITE_SPEECH		equ	2
ADDRESSABLE_LATCH_BIT_WRITE_KEYBOARD	equ	3
ADDRESSABLE_LATCH_ENABLE			equ	0
ADDRESSABLE_LATCH_DISABLE			equ	(1 << 3)

OSFILE_ACTION_SAVE_FILE			equ	0
OSFILE_ACTION_WRITE_CATALOGUE_INFO	equ	1
OSFILE_ACTION_WRITE_LOAD_ADDRESS	equ	2
OSFILE_ACTION_WRITE_EXEC_ADDRESS	equ	3
OSFILE_ACTION_WRITE_ATTRIBUTES	equ	4
OSFILE_ACTION_READ_CATALOGUE_INFO	equ	5
OSFILE_ACTION_DELETE_FILE		equ	6
OSFILE_ACTION_LOAD_FILE			equ	$ff

SYSTEM_VARIABLES				equ	$236

ZP_OS_IRQ_TEMP_A		equ	$fc

TUBE_PROTOCOL_CMD_OSFILE	equ	$14
