INTRO_SCREEN_MODE			equ	1

	SET_SCREEN_MODE_CONSTANTS	INTRO_SCREEN_MODE
INTRO_SCREEN_PIXELS_PER_BYTE	equ	SCREEN_PIXELS_PER_BYTE

INTRO_SCREEN_PIXEL_WIDTH	equ	256
INTRO_SCREEN_PIXEL_HEIGHT	equ	256
INTRO_SCREEN_PIXEL_HEIGHT_EX	equ	256 - 16

INTRO_SCREEN_ROWS			equ	(INTRO_SCREEN_PIXEL_HEIGHT + 7) / 8
INTRO_SCREEN_ROWS_EX		equ	(INTRO_SCREEN_PIXEL_HEIGHT_EX + 7) / 8

.ifdef NEVER
INTRO_SCREEN_COLUMNS_PER_ROW	equ	SCREEN_COLUMNS_PER_ROW

INTRO_SCREEN_START_ADDRESS	equ	$8000 - (INTRO_SCREEN_ROWS * 8 * INTRO_SCREEN_BYTES_PER_ROW)

INTRO_SCREEN_DRAW_ADDRESS	equ	INTRO_SCREEN_START_ADDRESS + (2 * INTRO_SCREEN_BYTES_PER_ROW)

.endif

INTRO_SCREEN_BYTE_COLUMNS	equ	INTRO_SCREEN_PIXEL_WIDTH / INTRO_SCREEN_PIXELS_PER_BYTE

INTRO_SCREEN_ACTUAL_ROWS	equ	INTRO_SCREEN_ROWS
INTRO_SCREEN_DISPLAYED_ROWS	equ	INTRO_SCREEN_ROWS_EX
INTRO_SCREEN_BYTES_PER_ROW	equ	(INTRO_SCREEN_BYTE_COLUMNS * 8)
INTRO_SCREEN_START_ADDRESS	equ	$8000 - (INTRO_SCREEN_BYTES_PER_ROW * INTRO_SCREEN_ACTUAL_ROWS)
INTRO_SCREEN_DRAW_ADDRESS	equ	INTRO_SCREEN_START_ADDRESS + (2 * INTRO_SCREEN_BYTES_PER_ROW)

